### ISSUE TITLE
[Ask] Probe Sensor

### ISSUE THREAD

**Issue by isnuryusuf** [Infor-Tech/Aquarium-Auto-Refill#5]
Hi, nice work for your project, i just want to asking for this ATO. which better sensor?
1. HC-SR04
2. XKC Y25 SENSOR / XKC-Y23
3. Type NPN : 5-12V DC
4. or standar FLOAT SWITCH SENSOR

**Comment by Infor-Tech** [comment]
### Hi @isnuryusuf 

To be honest, **HC-SR04** failed at it's task. It might not be a problem of hardware itself (distances between levels in my aquarium might be too small and usage of cm as a measurement unit was wrong).

After quick research **XKC Y25 SENSOR / XKC-Y23** seems to be a really good "tool for it's job", although I have no experience with this sensor, so I cannot recommend or discourage you from using this sensor in your recreation of this project. Just so you know code is not prepared for usage of this sensor, but you can contribute to this repo and add compatibility.

I don't know what do you mean by **"Type NPN: 5-12V DC"**, so if you could say something more, or just send me a link to this sensor it would be great.

I don't trust mechanical devices, such as float switches since they might lock in one position thus making false readings. Of course I might be just biased and this might be a really rare situation, but I wouldn't use this type of sensor.
